Сделал разметку
htmlacademy-htmlcss/2263523-sedona-36 pull request #2
Opened 2023-01-26 19:20 UTC by dewstrouk

сделал разметку

2023-01-27 04:54 UTC, Dima-Dim reviewed
Основные вопросы на данный момент:
1. Расставить отступы в файлах согласно стайлгайду Академии.
2. Выделить пункты списков.

2023-01-27 04:54 UTC, Dima-Dim commented on index.html
> +<ul class="navigation-list">
Отступы лучше с самого начала расставлять по правилам, чтобы потом эти не значимые изменения не отвлекали от всего остального. Не говоря уже о том, что с нормальными отступами и код читать проще.

2023-01-27 04:54 UTC, Dima-Dim commented on index.html
> +          <span class="visually-hidden">ХОЧУ СЮДА!</span></a>
Тексты нужно писать как в обычных предложениях, стилизацию будем делать с помощью css.

2023-01-27 04:54 UTC, Dima-Dim commented on index.html
> +<h3 class="advantages-title">Небольшая
Это похоже уже на следующий пункт списка.

2023-01-27 04:54 UTC, Dima-Dim commented on index.html
> +    <h2 class="visually-hidden">Преимущества</h2>
Вторая секция с преимуществами это странно. Если это всё ещё преимущества, то размещать их нужно в той же секции.

2023-01-27 04:54 UTC, Dima-Dim commented on index.html
> +        <a class="navigation-link" href="#">
Нет по макету тут ссылок.

2023-01-27 04:54 UTC, Dima-Dim commented on index.html
> +      <h2>+7 (812) 812-12-12</h2>
https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-03

2023-01-27 04:54 UTC, Dima-Dim commented on catalog.html
> +        <a class="navigation-logo" href="index.html"></a>
Кажется изображение должно быть внутри ссылки.

2023-01-27 04:54 UTC, Dima-Dim commented on catalog.html
> +          <button class="button" type="submit">Показать</button>
Нет же в макете кнопки "Показать".

2023-01-27 04:54 UTC, Dima-Dim commented on catalog.html
> +        </form>
А дальше уже не часть формы? Как оно будет работать?

2023-01-27 04:54 UTC, Dima-Dim commented on catalog.html
> +        <button class="button" type="submit">Сбросить</button>
Вряд ли пользователь ожидает отправку форму по кнопке с текстом Сбросить.

2023-01-31 05:21 UTC, Dima-Dim requested changes
Вернуть на место отступы в html коде, в соответствии со стайлгайдом Акадекии. Сейчас это нечитаемый код.

2023-02-03 04:06 UTC, Dima-Dim requested changes
[catalog.html](https://github.com/htmlacademy-htmlcss/2263523-sedona-36/pull/2/files#diff-8dc27294c839a5148fddb0dd53254501b8ef46d5eefb031ce7b6d0ce9f073cfe) - расставить отступы по стайлгайду Академии https://codeguide.academy/html-css.html#formatting.
с index.html тоже такая же проблема.
О том как сделать это просто либо должны были рассказывать, либо информация должна быть в материалах.

[image/Pagination-1.svg](https://github.com/htmlacademy-htmlcss/2263523-sedona-36/pull/2/files#diff-8ae1a97e1f156b893049b72ffaf77f3b8e85da2c985aed23f4cafd37cb775a2c) - https://up.htmlacademy.ru/htmlcss/36/criteries#PROJ-03
и зачем нам вообще изображение залитого одним цветом квадрата. Это можно сделать с помощью css.

[image/arrow..svg](https://github.com/htmlacademy-htmlcss/2263523-sedona-36/pull/2/files#diff-51c5bbb5f0494bfe86264fbd7abd1e01aa70e320df72a8420334e5889ad10931) одна точка в названии файла лишняя.

2023-02-03 04:06 UTC, Dima-Dim commented on index.html
> +    <img class="image" src="image/search.svg" width="44" height="64" alt="Поиск">
https://up.htmlacademy.ru/htmlcss/36/module/2/item/19

2023-02-03 04:06 UTC, Dima-Dim commented on index.html
> +   <span class="visually-hidden">Жилье</span></a>
Зачем тут этот скрытый текст?

2023-02-03 04:06 UTC, Dima-Dim commented on index.html
> +   <a class="button button-all" href="#">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</a>
Тексты нужно писать как в обычных предложениях, стилизацию будем делать с помощью css.

2023-02-03 04:06 UTC, Dima-Dim commented on catalog.html
> + <img class="image" src="#" alt="горы">
https://up.htmlacademy.ru/htmlcss/36/module/2/item/19

2023-02-03 04:06 UTC, Dima-Dim commented on catalog.html
> + <control class="control" type="submit">Сбросить</control>
Для чего тут тег `control` ?

2023-02-04 08:10 UTC, dewstrouk commented on catalog.html
> + <control class="control" type="submit">Сбросить</control>
потому что это кнопка, и вы сказали что <button> не подходит

2023-02-04 08:20 UTC, dewstrouk commented on index.html
> +    <img class="image" src="image/search.svg" width="44" height="64" alt="Поиск">
наверное я туплю, совсем не понимаю как мне исправить код и сделать правильные отступы(( help

2023-02-04 08:27 UTC, dewstrouk commented on index.html
> +    <img class="image" src="image/search.svg" width="44" height="64" alt="Поиск">
то есть здесь совсем убрать тег с картинкой , и все через css потом ??

2023-02-05 02:42 UTC, Dima-Dim commented on index.html
> +    <img class="image" src="image/search.svg" width="44" height="64" alt="Поиск">
Да, изображение нужно убрать, отступы будут дальше по программе.

2023-02-05 02:43 UTC, Dima-Dim commented on catalog.html
> + <control class="control" type="submit">Сбросить</control>
Не подходит что?

2023-02-05 03:22 UTC, Dima-Dim requested changes
[image/Pagination-1.svg](https://github.com/htmlacademy-htmlcss/2263523-sedona-36/pull/2/files#diff-8ae1a97e1f156b893049b72ffaf77f3b8e85da2c985aed23f4cafd37cb775a2c) - всё ещё есть.
зачем нам два одинаковых изображения [image/logo-header.jpg](https://github.com/htmlacademy-htmlcss/2263523-sedona-36/pull/2/files#diff-9c4e192462a4f90a1111810ef1dd96129ce7a505299bf45fe5916fa7f1f09c29) и [image/logo-header-2.jpg](https://github.com/htmlacademy-htmlcss/2263523-sedona-36/pull/2/files#diff-8d4ccf2f6158d334e42d8eb8626dfd4c6cc3dab92a8374852dd1400d4f50b505) и оно точно не доступно в svg?

2023-02-05 03:22 UTC, Dima-Dim commented on index.html
> +            <h3 class="advantages-title">Небольшая
Тут начинается вложенный список.

2023-02-05 03:22 UTC, Dima-Dim commented on index.html
> +            <a class="navigation-link" href="#">
Не вижу эту ссылку на макете.

2023-02-05 03:22 UTC, Dima-Dim commented on index.html
> +            <h3 class="features-title">Еда</h3>
Это следующий пункт списка.

2023-02-05 03:22 UTC, Dima-Dim commented on index.html
> +        <ul class="features-list">
Список из одного элемента?

2023-02-05 03:22 UTC, Dima-Dim commented on index.html
> +        <img class="subscription-logo" src="" alt="Фото каньона">
Это явно фоновое изображение, которое не нужно в разметке.

2023-02-05 11:33 UTC, dewstrouk commented on catalog.html
> + <control class="control" type="submit">Сбросить</control>
<button class="button" type="submit">Применить</button>
было тоже самое только сбросить , но сказали не так

2023-02-06 14:59 UTC, Dima-Dim requested changes

2023-02-06 14:59 UTC, Dima-Dim commented on index.html
> +            <span class="visually-hidden">Жильё</span>
Для чего эти ссылки? Покажи мне их в макете, пожалуйста.

2023-02-07 08:02 UTC, dewstrouk commented on index.html
> +            <span class="visually-hidden">Жильё</span>
какие ссылки ? тут же список , ссылки это же тег "а"

2023-02-08 03:52 UTC, Dima-Dim commented on catalog.html
> + <control class="control" type="submit">Сбросить</control>
Да, нужно исправить, но не тег, а его атрибут.

2023-02-08 03:55 UTC, Dima-Dim commented on index.html
> +            <span class="visually-hidden">Жильё</span>
Тут `<span class="visually-hidden">Жильё</span>`, в следующем пункте `<span class="visually-hidden">Еда</span></a>`, далее `<span class="visually-hidden">Сувениры</span>`, глаз зацепился за `</a>` видимо в связи с ними, тут появились эти span-ы. `</a>` был убраны, а span-ы остались. Дак для чего это всё тут?

2023-02-09 05:14 UTC, Dima-Dim requested changes
Сделать валидация html.
Подумать над названиями классов с цифрами, в первую очередь.
Использовать форматирование кода по кодгайду Академии.

2023-02-09 05:14 UTC, Dima-Dim commented on catalog.html
> +        <div class="found">
Для чего это div? Почему нельзя обойтись без него?

2023-02-09 05:14 UTC, Dima-Dim commented on catalog.html
>          </a>
validator.w3.org/nu/

2023-02-09 05:14 UTC, Dima-Dim commented on catalog.html
> +            <button class="button-card-blue" type="submit">в избранном</button>
Если придёт дизайнер и попросит сделать кнопку зелёной будешь переименовывать класс?

2023-02-09 05:14 UTC, Dima-Dim commented on catalog.html
> +          <li class="product-card-4">
Для учёта порядкового номер тега есть псевдоклассы https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements

2023-02-09 05:14 UTC, Dima-Dim commented on index.html
> +      <div class="text-1">
Если будешь смотреть в css без html поймёшь для чего это класс?

2023-02-09 05:14 UTC, Dima-Dim commented on styles/styles.css
> +color: #000000;
Форматирование кода должно быть одинаковым и по код гайду Академии.

2023-02-09 05:14 UTC, Dima-Dim commented on styles/styles.css
> +font-family: 'PT Sans';
Не нужно описывать те параметры которые можно не описывать. Если ты не укажет тут `font-family` он будет каким-то другим?

2023-02-09 09:30 UTC, dewstrouk commented on index.html
> +      <div class="text-1">
если это моя разметка , то конечно пойму) 
и я не всегда понимаю что нужно исправлять, и прошу немного больше подсказывать. Так я больше со всем разберусь)

2023-02-10 04:19 UTC, Dima-Dim commented on index.html
> +      <div class="text-1">
Очень редко такое бывать, что один разработчик и верстает сайт и интегрирует его с каким либо фреймворком или CMS, а потом ещё и поддерживает. Увидев такое название класса может возникнуть большое количество вопросов, для чего он, где используется и т.п. Ты можешь оставить и такое название класса, кажется это не противоречит критериям, но я предлагают на будущее подумать об этом. Тема нейминга одна из самых важных в программировании, от части потому, что позволяет экономить время в будущем.

2023-02-12 18:55 UTC, dewstrouk commented
Если все плоха, то мне скорее всего нужна ваша консультация)

2023-02-14 05:40 UTC, Dima-Dim commented
> Если все плоха, то мне скорее всего нужна ваша консультация)

Плохо не всё, а то, к чему оставлены комментарии.
Есть список того, что остаётся непонятным?

2023-02-14 05:41 UTC, Dima-Dim commented
Не вижу что после внесения правок html был проверен валидатором.
validator.w3.org/nu/

2023-02-15 04:16 UTC, Dima-Dim requested changes
После этого задания большие блоки страниц должны стоять на своих местах, как на макете, сейчас это ещё далеко от этого.

2023-02-15 04:16 UTC, Dima-Dim commented on index.html
> +          <form class="button-header">
Чего вдруг? Не было же не про что подобное замечаний? Какие данные эта форма будет отправлять? По такому принципу любые интерактивные элементы формой нужно делать.

2023-02-15 04:16 UTC, Dima-Dim commented on index.html
> +          <div class="text-1">
Если появился section, то div, с очень большой вероятностью буден не нужен.

2023-02-15 04:16 UTC, Dima-Dim commented on index.html
> +          <div class="text-3">
Тоже лишний div.

2023-02-15 04:16 UTC, Dima-Dim commented on index.html
> +            <form class="button-all">
Тоже форма без данных.

2023-02-15 04:16 UTC, Dima-Dim commented on styles/styles.css
> +  flex-direction: row;
Не понятно зачем это тут, но я надеюсь что ты изменишь разметку и это тоже уйдёт.

2023-02-19 14:24 UTC, Dima-Dim commented
У тебя всего 1 закрытый пуллриквес, про рабочий процесс и сейчас это как будто бы "Микросетки на флексах для всех страниц". Мы с html разметкой ещё не разобрались.

2023-02-19 14:37 UTC, Dima-Dim requested changes

2023-02-19 14:37 UTC, Dima-Dim commented on catalog.html
> +              <span class="visually-hidden">Поиск</span></a>
https://codeguide.academy/html-css.html#html-tags-formatting
Закрытие тега `a` должно быть на новой строке:
```
<a class="navigation-link" href="#">
  <span class="visually-hidden">Поиск</span>
</a>
```

2023-02-19 14:37 UTC, Dima-Dim commented on catalog.html
> +        <button class="control" value="Сбросить">Сбросить</button>
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type

2023-02-19 14:37 UTC, Dima-Dim commented on catalog.html
> +        <div class="found">
Не исправлено.

2023-02-19 14:37 UTC, Dima-Dim commented on catalog.html
> +            </a>
Что закрывает этот `</a>`?
https://validator.w3.org/nu/#textarea - покажет не только эту ошибку.

2023-02-19 14:37 UTC, Dima-Dim commented on catalog.html
> +            <form class="product-form" action="https://echo.htmlacademy.ru/" method="post">
Тоже нет тут формы.

2023-02-19 14:37 UTC, Dima-Dim commented on catalog.html
> +              <input class="rating" type="range" min="1" max="5" step="1">
Это статичные значения, никто тут ничего не вводит.

2023-02-19 14:37 UTC, Dima-Dim commented on catalog.html
> +        <form class="subscription-form" action="https://echo.htmlacademy.ru/" method="post">
Вот тут действительно форма :)

2023-02-19 14:37 UTC, Dima-Dim commented on index.html
> +          <form class="button-form" action="https://echo.htmlacademy.ru/" method="post">
Тоже не форма.

2023-02-19 14:37 UTC, Dima-Dim commented on index.html
> +      <div class="page-footer-container">
https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06

2023-02-19 14:37 UTC, Dima-Dim commented on styles/styles.css
> +@@ -0,
Что это?

2023-02-19 14:37 UTC, Dima-Dim commented on styles/styles.css
> +  font-family: 'PT Sans';
Точно нужно указать ` font-family`? Не наследуется от `body`?

2023-02-19 14:37 UTC, Dima-Dim commented on styles/styles.css
> +  height: 3556.86px;
А если контента будет больше чем на 3556,86px? И откуда такая точность до сотых?

2023-02-20 14:31 UTC, Dima-Dim requested changes

2023-02-20 14:31 UTC, Dima-Dim commented on catalog.html
> +            <a class="navigation-link" href="#"></a>
Почему ссылка стала пустой?

2023-02-20 14:31 UTC, Dima-Dim commented on catalog.html
> +            <button class="button-card" type="submit">подробнее</button>
Почему type="submit"? Какую форму отправляем?

2023-02-20 14:31 UTC, Dima-Dim commented on catalog.html
> +            <input type="text" value="РЕЙТИНГ: 8,5">
Тут никто ничего не вводит, это статическая информация.

2023-02-20 14:31 UTC, Dima-Dim commented on index.html
> +          <button class="button-all" type="submit">Поиск гостиницы в Седоне</button>
Тоже не понятно почему type="submit".

2023-02-20 20:14 UTC, dewstrouk commented on catalog.html
> +        <button class="control" value="Сбросить">Сбросить</button>
Там все на английском , тяжело разобраться (( и что в итоге с консультацией ? телеграмм ваш так и не находит , что делать и как быть??

2023-02-20 20:30 UTC, dewstrouk commented
На данном этапе я многое еще не понимаю , и мне нужно чтобы вы объяснили , без этого я не разберусь,

2023-02-21 15:05 UTC, Dima-Dim commented on catalog.html
> +        <button class="control" value="Сбросить">Сбросить</button>
Можно переключить на русский и будет на русском:
https://developer.mozilla.org/ru/docs/Web/HTML/Element/button
Примерно как же и с Телеграмом, нужно всего лишь кликнуть по иконке в контактах. Куратор обещал разобраться с этим и помочь.
А вообще английский это основной язык на котором вся информация и на котором все языки программирования, так что без его освоения в IT будет не просо, если вообще будет. К счастью сейчас есть онлайн переводчики, которые могут переводить хоть с картинок. Было бы желание ;)

2023-02-21 15:07 UTC, Dima-Dim commented
> На данном этапе я многое еще не понимаю , и мне нужно чтобы вы объяснили , без этого я не разберусь,

Составляй список вопросов и приходи в Телеграм, объясню. Можешь писать и на почту и тут, но там будет быстрее и удобнее.

2023-03-04 14:58 UTC, Dima-Dim requested changes
css файл сейчас бы убрать, потому что в задании со стилизацией уже написанные участки кода не будут отображены как добавленные. Можешь временно скопировать его себе куда-нибудь, а из проекта удалить. В следующем задании вернёшь.

Не забывай проверять html фалы валидатором validator.w3.org/nu

2023-03-04 14:58 UTC, Dima-Dim commented on catalog.html
> +            <form class="navigation-item" action="https://echo.htmlacademy.ru/" method="post">
Нет тут формы, просто кнопка/ссылка и она никакие данные никуда не отправляет.

2023-03-04 14:58 UTC, Dima-Dim commented on catalog.html
> +            <button class="button" type="button">Применить</button>
А вот эта кнопка как раз отправляет форму.

2023-03-04 14:58 UTC, Dima-Dim commented on catalog.html
> +                <input type="text" value="РЕЙТИНГ: 8,5">
Тут рейтинг просто отображается, данные не вводятся.

2023-03-04 14:58 UTC, Dima-Dim commented on catalog.html
> +          <div class="pagination-container">
Пока похоже на линий контейнер.

2023-03-04 14:58 UTC, Dima-Dim commented on catalog.html
> +            <input type="email" id="email" name="email" placeholder="Ваш email" required>
Не забыть label для этого input-а.

2023-03-04 14:58 UTC, Dima-Dim commented on index.html
> +        <div class="page-container">
Пока тоже сомнительный контейнер.

2023-03-04 14:58 UTC, Dima-Dim commented on index.html
> +            <ul class="advantages-list">
Список из одного пункта так себе список.

2023-03-04 14:58 UTC, Dima-Dim commented on index.html
> +                <section class="block-advantages">
Эти 3 пункта похоже на вложенный список.

2023-03-04 14:58 UTC, Dima-Dim commented on index.html
> +                <div class="advantages-container">
А это похоже на один из пунктов первого списка.

2023-03-04 14:58 UTC, Dima-Dim commented on index.html
> +          <section class="features">
Тоже похоже на список.

2023-03-04 14:58 UTC, Dima-Dim commented on index.html
> +            <div class="interested-text">
Тоже пока не понятный `div`.

2023-03-04 14:58 UTC, Dima-Dim commented on index.html
> +            <div class="text-4">
Тоже странный `div` на данном этапе, как минимум.

2023-03-05 14:34 UTC, dewstrouk commented on catalog.html
> +                <input type="text" value="РЕЙТИНГ: 8,5">
тогда через что сделать этот рейтинг, какой тег ?

2023-03-05 14:37 UTC, dewstrouk commented on catalog.html
> +          <div class="pagination-container">
не совсем понял что значит ( но когда стилизовал , вроде хорошо вышла пагинация

2023-03-05 16:40 UTC, dewstrouk commented on index.html
> +          <section class="features">
то есть h2 и p заменить на li ? и так во всех остальных таких же блоках ?

2023-03-05 16:43 UTC, dewstrouk commented on index.html
> +            <div class="interested-text">
А как быть ? тоже сделать списком ? или просто убрать div ?

2023-03-06 06:57 UTC, Dima-Dim commented on catalog.html
> +                <input type="text" value="РЕЙТИНГ: 8,5">
Например span. Это просто стилизованный элемент.

2023-03-06 06:58 UTC, Dima-Dim commented on catalog.html
> +          <div class="pagination-container">
Опечатался, имелось ввиду `лишний`, значит можно попробовать стилизовать и без него.

2023-03-06 06:59 UTC, Dima-Dim commented on index.html
> +          <section class="features">
Говорить что нужно заменить что-то на что-то не совсем верно. Нужно просто делать корректный список из логичных пунктов.

2023-03-06 07:00 UTC, Dima-Dim commented on index.html
> +            <div class="interested-text">
Просто убрать лишний контейнер, в данном случае `div`.

2023-03-07 15:23 UTC, Dima-Dim requested changes
Уже лучше, дорабатываем списки.

2023-03-07 15:23 UTC, Dima-Dim commented on catalog.html
> +            <form class="range-form" action="https://echo.htmlacademy.ru/" method="post">
Форма начинается на 58-ой строке.
Не забывай проверять html валидатором validator.w3.org/nu

2023-03-07 15:23 UTC, Dima-Dim commented on index.html
> +            <ul class="advantages-list">
Все преимущества это список. Ведь так и говорят "Список преимуществ". Заголовок, описание и изображение преимущества это не список. Это заголовок, описание и изображение элемента списка.
Представь список дел. У каждого дела есть название и что нужно сделать, а ещё иконка. Что будет являться писком, что его элементами. Тут такая же логика.

2023-03-09 16:15 UTC, Dima-Dim commented on catalog.html
> +          <form class="range-form" action="https://echo.htmlacademy.ru/" method="post">
Писал что форма начинается выше.

2023-03-09 16:17 UTC, merged

2023-03-09 19:16 UTC, dewstrouk commented on catalog.html
> +          <form class="range-form" action="https://echo.htmlacademy.ru/" method="post">
то есть все обернуть в форму начиная с 58 строки ??

2023-03-09 19:17 UTC, dewstrouk commented
дальше начинать стилизацию ? Разметка же вся готова ?

2023-03-18 04:15 UTC, Dima-Dim commented on catalog.html
> +          <form class="range-form" action="https://echo.htmlacademy.ru/" method="post">
Обернуть в теги form всё, что является формой. Именно в этом смысл тега form.